### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by nncrns** [jmheretik/kirby-vue-starterkit#12]
I am trying to deploy my Nuxt app using your starterkit. Unfortunately, I am getting two errors when I call the deployed website.

I am injecting into Kirby. So I did the following things:

1. **kirby.config.js**: `inject: true`
2. **kirby/site/config/config.php**: `'kirby-vue-starterkit.plugin.useVueIndex' => true` and changed my host to `host: 'http://my.staging-domain.com'`
3. Created **.env.production** with `NUXT_ENV_BASE_URL=/` and `NUXT_ENV_KIRBY_URL=http://my.staging-domain.com`
4. Ran `npm run build`
5. Deployed the `kirby` folder to my webspace

Now, when I call the website, I get

```
/home.json:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Error: Request failed with status code 500
    at t.exports (33a14a509ee646ff16f8.js:2)
    at t.exports (33a14a509ee646ff16f8.js:2)
    at XMLHttpRequest._.onreadystatechange (33a14a509ee646ff16f8.js:2)
```

Any ideas about what I'm doing wrong? I am deploying to the root of a subdomain, so I don't think that this would affect `NUXT_ENV_BASE_URL`, right?

**Edit:** I forgot to mention that the site skeleton of index.vue is correctly loaded, including scripts and styles. It can just not access the json.

Thanks so much in advance! 🙏

**Comment by jmheretik** [comment]
Hi. I'm sorry but I can't replicate the issue.

What happens if you visit http://my.staging-domain.com/home.json directly?

Could you maybe send me the real public URL where it's deployed?

**Comment by nncrns** [comment]
Yes, sorry – I made an error in step 2, I had of course changed the host in `kirby.config.js` (not `config.php`). I have now reversed this step. Otherwise, I did everything as described above. 

The URL is `http://pm.annacairns.com/`. If I visit `http://pm.annacairns.com/home.json` I get a 500 Internal Server Error.

**Comment by jmheretik** [comment]
I think it's a problem with your hosting because even the Kirby error handler doesn't get loaded so there is already an error on the php part... And on a subpage - something like http://pm.annacairns.com/notes nothing gets loaded, not even assets or anything. Can you try to upload just the original Kirby starterkit (without vue)?

Error 500 could have a million different reasons so I can't really help here. Maybe check if the mod_rewrite is available on your php hosting? (just a wild guess)

**Comment by nncrns** [comment]
Great idea, this got me on the right track to solve it! I simply had to activate `RewriteBase /` in `.htaccess` (which is commented out by default).

Thanks so much :) Hope this helps others facing the same issue (maybe worth a mention in the docs?).

**Comment by jmheretik** [comment]
Glad you got it sorted!

Yeah, I'm thinking of writing down some list of links or FAQ as prerequisities to understand before using this template. So that I don't repeat what has already been said. Your problem is for example here already: https://getkirby.com/docs/guide/troubleshooting/installation#broken-subpages
