### ISSUE TITLE
Nuxt SSR || KQL

### ISSUE THREAD

**Issue by jonasfeige** [jmheretik/kirby-vue-starterkit#19]
Hi there, thanks so much for these starterkits, they are super helpful.
At the risk of sounding presumptuous, did you ever consider a Nuxt SSR version or one using the KQL plugin?

**Comment by jmheretik** [comment]
Hi, i'm glad you find it useful :)
I am thinking about SSR, even discussed it before briefly here https://github.com/jmheretik/kirby-vue-starterkit/issues/7#issuecomment-631414391, but unfortunately didn't get the time yet to get properly on it.

As the KQL plugin goes, I'm not familiar with this at all - what is it?

**Comment by jonasfeige** [comment]
it’s a query language plugin for the Kirby API:
[https://github.com/getkirby/kql](Kirby QL)

SSR would be amazing, if you ever get the chance! :)

**Comment by jmheretik** [comment]
:O this looks very nice - it's exactly the kind of syntax i wished for when working with kirby's rest api 😄 do you know if there are any plans of them integrating this eventually into kirby api itself?

**Comment by jonasfeige** [comment]
I don’t know, but it is developed by the creator of Kirby himself, so I think it’s definitely there to stay!

**Comment by johannschopplich** [comment]
KQL will not be integrated into the core (apart from the Editor, which will be somewhere in the future when the teams dropped the ProseMirror dependency), but will always be supported as a plug-in. Bastian states that in numerous comments I read. 

Since KQL's creation in December, many users have used it successfully, even if Bastian declared it as still in alpha. Some weeks ago he released the beta. As far as I can tell, it's pretty stable!

**Comment by Maybach91** [comment]
Are there any updates / plans on this @jmheretik ?

**Comment by jmheretik** [comment]
@Maybach91 Hi, I'm sorry, but I have no updates or plans in the near future concerning this as I have no free time right now 😞
