### ISSUE TITLE
Accessing the panel

### ISSUE THREAD

**Issue by zhampu** [jmheretik/kirby-vue-starterkit#4]
Hey,
Great idea for a template!
I can't connect the panel as im getting this error runnning Serve:backend 

`  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80
}
`
If i change the kirby.config to 127.0.0.2 it works but when running serve:frontend  and og to /panel theres nothing there.

Any idea how can I overcome this ?

**Comment by jmheretik** [comment]
Hello,
maybe you have some other application running on that host or port?

Recently I made some radical changes in the folder structure and wrote new README docs for this project (sorry, I didn't know people are actually using this template :). So could you please pull the recent changes, check the docs and try to run it again to see if the problem persists? Hopefully it's fixed by now.
