### ISSUE TITLE
Proposal: Replace `node-php-server` with maintained package

### ISSUE THREAD

**Issue by johannschopplich** [jmheretik/kirby-vue-starterkit#6]
I was just about to push a pull request when you updated code which I was working on. 😄 So why not create a proposal first.

Since `node-php-server` isn't maintained anymore and a better package by the awesome Sindre Sorhus exists, why not switch to `php-server`. A advantage is to let the script kill the PHP server automatically. Therefore you could drop the Nuxt hook. The setup would be:

```js
const phpServer = require('php-server')
start: () => {
  const server = await phpServer({
    hostname: module.exports.host,
    port: module.exports.port,
    base: module.exports.base,
    router: module.exports.routerPath
  })

  console.log('\x1b[32m%s\x1b[0m', `Kirby running at ${server.url}\n`)
},
```

I also changed the console log to green to differentiate normal texts from the starting server.

Your continuous work on this project is amazing. It's so much fun following the progress and all the new ideas your put in. Keep up the great work!

**Comment by jmheretik** [comment]
Hello again!

Sorry for that, I didn't know people are actually using this template :) and recently I've been making some radical changes directly in the master branch, so I'll do them in different branch in the future.

I would love to get rid of the `node-php-server` package, since I already bumbed into more issues while working with it. The reason for it being here in the first place is that it was the only working one I could find back then when I started this project. Or maybe I just didn't search the npm thoroughly enough :)

I'll definitely check out the one you're proposing. And thanks for the support - it's a great motivation for me :)

**Comment by johannschopplich** [comment]
Hey there!

Haha, no problem. 🙂 I have discovered the `php-server` package only recently, while I was searching for an alternative of the unmaintained one. 

I can assure you others are using your template. At least I do. I've created a fork with accessible routing, custom folder setup, SEO, and an offline-first service worker (not using Vue CLI PWA but custom Workbox script) which is based heavily on your project: [Accessible Kirby Vue Starterkit](https://github.com/johannschopplich/aria-kirby-vue-starterkit)

Again, thanks for all the work you put into this template. I have learned so much! And I'm looking forward for future commits to explore. Two projects I've created at work are based on your project.
