### ISSUE TITLE
Default admin user

### ISSUE THREAD

**Issue by oemueller** [jmheretik/kirby-vue-starterkit#8]
Really usefull starterkit!
I was struggling with login into the panel because there is only the API user. 
Can we add a default Admin user maybe? 
They only way I found to add a admin user was to copy a user from another Kirby project 🙂
What do you think?

**Comment by gman900** [comment]
I had the same problem. I was initially confused about how I would log in to the panel. I ended up just deleting the API user. Once I'd done this Kirby just prompted me to create a new user. Maybe a bit about this in the docs would be useful?

**Comment by jmheretik** [comment]
Hey guys, I'm sorry. I actually added the preconfigured API user just recently - thinking that it would simplify the setup even more. But I didn't realize that then there is no real/admin user and kirby doesn't prompt you anymore to create one because it has one already.

I removed the API user and updated the docs explaining how to create it :-) Thanks for pointing this out.
